# Generated by Django 3.2.7 on 2021-11-08 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderplaced',
            old_name='Customer',
            new_name='customer',
        ),
        migrations.AlterField(
            model_name='product',
            name='catagory',
            field=models.CharField(choices=[('M', 'Mobile'), ('L', 'Laptop'), ('TW', 'Top Wear'), ('BW', 'Bottom Wear'), ('C', 'Camera'), ('W', 'Watch'), ('B', 'Bag'), ('C', 'Cosmetics')], max_length=10),
        ),
    ]
