# Generated by Django 3.2.7 on 2021-11-10 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_orderplaced_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='catagory',
            field=models.CharField(choices=[('M', 'Mobile'), ('L', 'Laptop'), ('TW', 'Top Wear'), ('BW', 'Bottom Wear'), ('CM', 'Camera'), ('W', 'Watch'), ('B', 'Bag'), ('C', 'Cosmetics')], max_length=10),
        ),
    ]
